services:
  web:
    build: .
    container_name: django_app
    expose:
      - "8000"

  nginx:
    image: nginx:1.29
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
